version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: schedy
    main: ./cmd/schedy/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    binary: schedy

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: ksamirdev
    name: schedy
  draft: false
  prerelease: false
  footer: |
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

checksum:
  name_template: "checksums.txt"
