name: Build on PR and Release

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: schedy

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get latest Git tag (skip on PR)
        id: get_tag
        if: github.event_name != 'pull_request'
        run: |
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            ${{ github.event_name != 'pull_request' && format('docker.io/{0}/schedy', secrets.DOCKERHUB_USERNAME) || '' }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha
            ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && 'latest' || '' }}
            ${{ github.event_name == 'workflow_dispatch' && steps.get_tag.outputs.tag || '' }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: |
            ${{ github.event_name == 'pull_request' && 'type=registry,push=false' || '' }}
