name: Cleanup Container Images
on:
  schedule:
    - cron: "0 0 * * 0" # Weekly
  workflow_dispatch:
    inputs:
      dry-run:
        description: "List what would be deleted without deleting"
        type: boolean
        default: true

jobs:
  cleanup-pr-and-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Delete PR and branch images
        uses: snok/container-retention-policy@v3.1.0
        with:
          account: user
          token: ${{ secrets.GHCR_CLEANUP_TOKEN }}
          image-names: schedy
          image-tags: "pr-*,main,sha-*"
          tag-selection: tagged
          cut-off: 1d
          keep-n-most-recent: 0
          dry-run: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run || 'false' }}

  cleanup-untagged:
    runs-on: ubuntu-latest
    steps:
      - name: Delete untagged images
        uses: snok/container-retention-policy@v3.1.0
        with:
          account: user
          token: ${{ secrets.GHCR_CLEANUP_TOKEN }}
          image-names: schedy
          tag-selection: untagged
          cut-off: 1d
          keep-n-most-recent: 0
          dry-run: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run || 'false' }}
